import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#f6ede1" },
  scrollView: { flex: 1 },
  scrollContent: { padding: 20, gap: 18 },
  scrollContentTablet: {
    paddingHorizontal: 28,
    paddingTop: 26,
    paddingBottom: 30,
  },
  scrollContentDesktop: {
    width: "100%",
    maxWidth: 1320,
    alignSelf: "center",
    paddingHorizontal: 32,
  },
  loadingShell: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f6ede1",
    gap: 12,
  },
  loadingLabel: { fontSize: 16, color: "#5d4a38" },
  backgroundOrbA: {
    position: "absolute",
    top: -50,
    right: -20,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "#f1c28d",
    opacity: 0.35,
  },
  backgroundOrbB: {
    position: "absolute",
    bottom: 90,
    left: -50,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "#d2e4d1",
    opacity: 0.45,
  },
  heroCard: {
    backgroundColor: "#fff8f1",
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    borderColor: "#e8d7bf",
    shadowColor: "#7c5230",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  heroCardDesktop: {
    padding: 28,
  },
  eyebrow: {
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: "#b45e20",
    fontWeight: "700",
    marginBottom: 10,
  },
  heroTitle: {
    fontSize: 30,
    lineHeight: 36,
    color: "#2f2318",
    fontFamily: "serif",
    fontWeight: "700",
  },
  heroSubtitle: { marginTop: 10, color: "#5d4a38", fontSize: 15, lineHeight: 22 },
  heroChecklist: {
    marginTop: 14,
    gap: 6,
  },
  heroChecklistItem: {
    color: "#6a5642",
    fontSize: 13,
    lineHeight: 20,
  },
  heroActions: { flexDirection: "row", gap: 10, marginTop: 18, flexWrap: "wrap" },
  serverHint: { marginTop: 14, color: "#7c6a55", fontSize: 12 },
  workspaceToolbar: {
    backgroundColor: "#fff8f1",
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: "#e8d7bf",
    gap: 18,
  },
  workspaceToolbarDesktop: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  workspaceToolbarMain: {
    flex: 1,
    gap: 12,
  },
  workspaceToolbarTitle: {
    fontSize: 20,
    lineHeight: 26,
    color: "#2f2318",
    fontFamily: "serif",
    fontWeight: "700",
  },
  workspaceToolbarBody: {
    color: "#5d4a38",
    lineHeight: 22,
  },
  workspaceToolbarActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  workspaceToolbarHint: {
    color: "#7c6a55",
    fontSize: 12,
  },
  workspaceToolbarStats: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    alignItems: "stretch",
  },
  workspaceStatCard: {
    minWidth: 86,
    borderRadius: 18,
    backgroundColor: "#f7efe5",
    borderWidth: 1,
    borderColor: "#e6d6c0",
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  workspaceStatValue: {
    fontSize: 22,
    lineHeight: 26,
    color: "#2f2318",
    fontWeight: "800",
  },
  workspaceStatLabel: {
    color: "#75624f",
    fontSize: 12,
    fontWeight: "700",
  },
  noticeBox: {
    marginTop: 12,
    borderRadius: 14,
    backgroundColor: "#f5e4d2",
    color: "#6d3d17",
    paddingHorizontal: 12,
    paddingVertical: 10,
    lineHeight: 20,
  },
  primaryButton: {
    backgroundColor: "#b75e1f",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryButtonLabel: { color: "#fffaf4", fontWeight: "700" },
  disabledButtonLabel: { opacity: 0.55 },
  secondaryButton: {
    backgroundColor: "#efe1d1",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  secondaryButtonLabel: { color: "#5a3f2a", fontWeight: "700" },
  sectionRow: { gap: 18 },
  sectionRowDesktop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  column: { gap: 10 },
  columnWide: { gap: 10, flex: 1 },
  detailColumnDesktop: {
    minWidth: 0,
    flex: 1,
  },
  listColumnDesktop: {
    width: 360,
    flexShrink: 0,
  },
  sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  detailHeaderBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sectionTitle: {
    fontSize: 22,
    color: "#2f2318",
    fontFamily: "serif",
    fontWeight: "700",
  },
  sectionMeta: { color: "#7c6a55", fontSize: 12, fontWeight: "700" },
  panel: {
    backgroundColor: "#fffbf7",
    borderWidth: 1,
    borderColor: "#eadcc6",
    borderRadius: 24,
    padding: 12,
    gap: 10,
  },
  listControlsShell: {
    gap: 10,
  },
  listControlsShellDesktop: {
    paddingBottom: 2,
  },
  listSelectionHint: {
    color: "#7d6954",
    fontSize: 12,
    lineHeight: 18,
  },
  listControlsDivider: {
    height: 1,
    backgroundColor: "#eadcc6",
  },
  listScrollArea: {
    minHeight: 120,
  },
  listScrollContent: {
    gap: 10,
    paddingBottom: 2,
  },
  jobTableHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingBottom: 2,
  },
  jobTableHeaderText: {
    color: "#8a7661",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  jobTableHeaderStatus: {
    width: 82,
    flexShrink: 0,
  },
  jobTableHeaderFilename: {
    flex: 1,
    minWidth: 0,
  },
  jobTableHeaderTimestamp: {
    width: 94,
    flexShrink: 0,
    textAlign: "right",
  },
  desktopPanelScrollArea: {
    maxHeight: 640,
  },
  listSearchInput: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#dcc9b0",
    backgroundColor: "#fffdfa",
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#2f2318",
  },
  listFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  listFilterChip: {
    borderRadius: 999,
    backgroundColor: "#f1e5d8",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  listFilterChipActive: {
    backgroundColor: "#2e6758",
  },
  listFilterChipLabel: {
    color: "#6f5a48",
    fontSize: 12,
    fontWeight: "700",
  },
  listFilterChipLabelActive: {
    color: "#fffaf4",
  },
  listSortButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d4c3ae",
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "#fff8f1",
  },
  listSortButtonLabel: {
    color: "#5a3f2a",
    fontWeight: "700",
    fontSize: 12,
  },
  panelLarge: {
    backgroundColor: "#fffbf7",
    borderWidth: 1,
    borderColor: "#eadcc6",
    borderRadius: 24,
    padding: 16,
    gap: 14,
    minHeight: 420,
  },
  panelLargeDesktop: {
    minHeight: 640,
  },
  stateCardNeutral: {
    borderRadius: 20,
    padding: 20,
    backgroundColor: "#f6efe8",
    gap: 8,
    borderWidth: 1,
    borderColor: "#eadcc6",
  },
  stateCardProcessing: {
    borderRadius: 20,
    backgroundColor: "#e4f2ef",
    padding: 18,
    gap: 10,
    borderWidth: 1,
    borderColor: "#b9d7d3",
  },
  stateCardError: {
    borderRadius: 20,
    backgroundColor: "#f7dfdc",
    padding: 18,
    gap: 10,
    borderWidth: 1,
    borderColor: "#dfb0aa",
  },
  stateCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  stateEyebrow: {
    color: "#7b664f",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
  },
  stateTitle: {
    fontSize: 20,
    lineHeight: 28,
    color: "#2f2318",
    fontFamily: "serif",
    fontWeight: "700",
  },
  stateBody: {
    color: "#5f5144",
    lineHeight: 22,
  },
  emptyDetailChecklist: {
    marginTop: 8,
    gap: 6,
  },
  emptyDetailChecklistItem: {
    color: "#6f5b48",
    lineHeight: 20,
  },
  progressSteps: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  progressStepsStack: {
    flexDirection: "column",
  },
  progressStep: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  progressStepActive: {
    backgroundColor: "#2e6758",
  },
  progressStepPending: {
    backgroundColor: "rgba(46, 103, 88, 0.12)",
  },
  progressStepLabel: {
    color: "#f7efe6",
    fontWeight: "700",
    fontSize: 12,
  },
  jobCard: { borderRadius: 18, backgroundColor: "#f8efe6", padding: 14, gap: 8 },
  jobCardSelected: { backgroundColor: "#f2dcc2", borderWidth: 1, borderColor: "#d19259" },
  jobRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 16,
    backgroundColor: "#f8efe6",
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "transparent",
  },
  jobRowSelected: {
    backgroundColor: "#f2dcc2",
    borderColor: "#d19259",
  },
  jobRowStatusCell: {
    width: 82,
    flexShrink: 0,
  },
  jobRowFilenameCell: {
    flex: 1,
    minWidth: 0,
  },
  jobRowTimestampCell: {
    width: 94,
    flexShrink: 0,
    alignItems: "flex-end",
  },
  jobCardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 },
  jobTimestamp: { color: "#887561", fontSize: 11 },
  jobFilename: { color: "#36281d", fontSize: 14, lineHeight: 19, fontWeight: "600" },
  loadMoreButton: { paddingVertical: 12, alignItems: "center" },
  loadMoreLabel: { color: "#8b5c2e", fontWeight: "700" },
  emptyState: { color: "#7c6a55", lineHeight: 22 },
  detailHeader: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  detailTopCluster: {
    gap: 12,
  },
  detailStickyShell: {
    gap: 12,
  },
  detailStickyShellDesktop: {
    paddingBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: "#eadcc6",
  },
  detailTopClusterDesktop: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 14,
  },
  detailControlsCluster: {
    flex: 1,
    gap: 12,
    minWidth: 0,
  },
  backButton: {
    backgroundColor: "#efe1d1",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  backButtonLabel: {
    color: "#5a3f2a",
    fontWeight: "700",
    fontSize: 12,
  },
  detailTitle: {
    fontSize: 21,
    lineHeight: 28,
    color: "#2f2318",
    fontFamily: "serif",
    fontWeight: "700",
  },
  detailSub: { marginTop: 6, color: "#887561" },
  processingBox: {
    borderRadius: 18,
    backgroundColor: "#e2f0ef",
    padding: 16,
    gap: 10,
    alignItems: "center",
  },
  processingLabel: { color: "#0f5656", textAlign: "center", lineHeight: 21 },
  errorBox: { borderRadius: 18, backgroundColor: "#f7dfdc", padding: 16, gap: 10 },
  errorTitle: { color: "#8e2020", fontWeight: "800", fontSize: 16 },
  errorBody: { color: "#713535", lineHeight: 20 },
  tabRow: { flexDirection: "row", gap: 8 },
  tabButton: {
    flex: 1,
    borderRadius: 999,
    paddingVertical: 12,
    backgroundColor: "#efe5d8",
    alignItems: "center",
  },
  tabButtonActive: { backgroundColor: "#2e6758" },
  tabLabel: { color: "#5a4535", fontWeight: "700" },
  tabLabelActive: { color: "#f8f5ef" },
  resultMetaCard: { borderRadius: 18, padding: 14, backgroundColor: "#f6efe8", gap: 6 },
  resultMetaCardDesktop: {
    width: 280,
    flexShrink: 0,
  },
  resultMetaEyebrow: {
    color: "#8a7661",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  resultMetaTitle: { color: "#34261c", fontSize: 18, fontWeight: "700" },
  resultMetaBody: { color: "#705a45", lineHeight: 20 },
  detailActionsHeader: {
    gap: 4,
  },
  detailActionsTitle: {
    color: "#2f2318",
    fontSize: 18,
    fontWeight: "700",
  },
  detailActionsHint: {
    color: "#75624f",
    lineHeight: 20,
  },
  toolbar: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  toolbarDesktopCompact: {
    justifyContent: "flex-start",
    alignItems: "center",
  },
  toolbarStack: {
    flexDirection: "column",
    alignItems: "stretch",
  },
  editorToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  editorToolbarDesktop: {
    gap: 12,
    alignItems: "stretch",
  },
  editorToolGroup: {
    borderRadius: 16,
    backgroundColor: "#f7efe5",
    borderWidth: 1,
    borderColor: "#e6d6c0",
    padding: 10,
    gap: 8,
  },
  editorToolGroupLabel: {
    color: "#8a7661",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  editorToolGroupButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  editorToolButton: {
    backgroundColor: "#f0e4d6",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  editorToolLabel: {
    color: "#5a3f2a",
    fontWeight: "700",
    fontSize: 12,
  },
  sectionJumpRow: {
    gap: 8,
    paddingVertical: 2,
  },
  sectionJumpButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#dbcbb5",
    backgroundColor: "#fff8f1",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  sectionJumpLabel: {
    color: "#705a45",
    fontSize: 12,
    fontWeight: "700",
  },
  editor: {
    minHeight: 220,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#d9c7ad",
    backgroundColor: "#fffdfa",
    padding: 14,
    fontSize: 14,
    lineHeight: 20,
    color: "#2f2318",
  },
  editorDesktop: {
    minHeight: 520,
    flex: 1,
  },
  editorSplitLayout: {
    flexDirection: "row",
    gap: 14,
    alignItems: "stretch",
    minHeight: 540,
  },
  editorPanel: {
    flex: 1,
    borderRadius: 20,
    backgroundColor: "#fffdfa",
    borderWidth: 1,
    borderColor: "#e4d4bf",
    padding: 14,
    gap: 10,
    minHeight: 0,
  },
  previewPanel: {
    borderRadius: 20,
    backgroundColor: "#fffdfa",
    borderWidth: 1,
    borderColor: "#e4d4bf",
    padding: 14,
    gap: 10,
    minHeight: 240,
  },
  previewPanelDesktop: {
    flex: 1,
    minHeight: 0,
  },
  previewPanelSplit: {
    minHeight: 540,
  },
  previewLabel: {
    color: "#7b664f",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  previewScroll: { maxHeight: 360 },
  previewScrollDesktop: {
    maxHeight: 520,
  },
  previewText: { color: "#2f2318", fontSize: 14, lineHeight: 21 },
  previewEmpty: { color: "#7c6a55", lineHeight: 22 },
  markdownPreview: { gap: 12 },
  markdownHeading: {
    color: "#2f2318",
    fontFamily: "serif",
    fontWeight: "700",
  },
  markdownHeading1: {
    fontSize: 26,
    lineHeight: 34,
  },
  markdownHeading2: {
    fontSize: 22,
    lineHeight: 30,
  },
  markdownHeading3: {
    fontSize: 18,
    lineHeight: 26,
  },
  markdownParagraph: {
    color: "#2f2318",
    fontSize: 15,
    lineHeight: 24,
  },
  markdownStrong: {
    fontWeight: "700",
    color: "#24190f",
  },
  markdownEmphasis: {
    fontStyle: "italic",
  },
  markdownStrike: {
    textDecorationLine: "line-through",
    color: "#7b7064",
  },
  markdownInlineCode: {
    fontFamily: "monospace",
    backgroundColor: "#f1e6d8",
    color: "#6d3d17",
  },
  markdownLink: {
    color: "#0f6f6f",
    textDecorationLine: "underline",
  },
  markdownCheckbox: {
    width: 18,
    height: 18,
    marginTop: 4,
    borderWidth: 1,
    borderColor: "#b5a695",
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fffdfa",
  },
  markdownCheckboxChecked: {
    backgroundColor: "#d7e8e2",
    borderColor: "#7aa396",
  },
  markdownCheckboxMark: {
    color: "#2e6758",
    fontSize: 12,
    fontWeight: "700",
  },
  markdownChecklistDone: {
    color: "#7b7064",
    textDecorationLine: "line-through",
  },
  markdownQuote: {
    borderLeftWidth: 3,
    borderLeftColor: "#cfc4b6",
    paddingVertical: 6,
    paddingLeft: 14,
    paddingRight: 4,
    marginVertical: 2,
  },
  markdownQuoteText: {
    color: "#6f6256",
    fontSize: 14,
    lineHeight: 22,
    fontStyle: "italic",
  },
  markdownQuoteParagraph: {
    marginTop: 8,
  },
  markdownList: {
    gap: 8,
  },
  markdownListItem: {
    flexDirection: "row",
    gap: 4,
    alignItems: "flex-start",
  },
  markdownListBullet: {
    minWidth: 14,
    color: "#8b5c2e",
    fontWeight: "700",
    lineHeight: 24,
  },
  markdownListText: {
    color: "#2f2318",
    fontSize: 15,
    lineHeight: 24,
  },
  markdownListTextWrap: {
    flex: 1,
  },
  markdownRule: {
    height: 1,
    backgroundColor: "#e3d2bc",
    marginVertical: 4,
  },
  markdownTable: {
    borderWidth: 1,
    borderColor: "#ddd6cc",
    borderRadius: 6,
    overflow: "hidden",
    backgroundColor: "#fffdfa",
  },
  markdownTableScrollContent: {
    minWidth: "100%",
  },
  markdownTableHeaderRow: {
    backgroundColor: "#f8f6f2",
  },
  markdownTableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e7e0d6",
  },
  markdownTableRowLast: {
    borderBottomWidth: 0,
  },
  markdownTableCell: {
    flex: 1,
    minWidth: 140,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRightWidth: 1,
    borderRightColor: "#e7e0d6",
    justifyContent: "center",
  },
  markdownTableHeaderCell: {
    borderBottomWidth: 1,
    borderBottomColor: "#d9d1c6",
  },
  markdownTableCellLast: {
    borderRightWidth: 0,
  },
  markdownTableHeaderText: {
    color: "#4f463d",
    fontWeight: "700",
    lineHeight: 20,
  },
  markdownTableCellText: {
    color: "#2f2318",
    lineHeight: 21,
  },
  markdownTableTextLeft: {
    textAlign: "left",
  },
  markdownTableTextCenter: {
    textAlign: "center",
  },
  markdownTableTextRight: {
    textAlign: "right",
  },
  markdownImageWrap: {
    gap: 8,
  },
  markdownImageFallback: {
    borderWidth: 1,
    borderColor: "#ddd6cc",
    borderRadius: 12,
    padding: 14,
    gap: 8,
    backgroundColor: "#fbf7f2",
  },
  markdownImageFallbackTitle: {
    color: "#5f5144",
    fontWeight: "700",
  },
  markdownImageFallbackUrl: {
    color: "#7b6a57",
    lineHeight: 18,
  },
  markdownImage: {
    width: "100%",
    minHeight: 180,
    maxHeight: 320,
    borderRadius: 12,
    backgroundColor: "#f7f2eb",
  },
  markdownImageCaption: {
    color: "#7b6a57",
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  editNotice: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  editNoticeDirty: {
    backgroundColor: "#f6e2cf",
  },
  editNoticeClean: {
    backgroundColor: "#e5f1ed",
  },
  editNoticeText: {
    color: "#5f5144",
    lineHeight: 20,
  },
  diffPreview: {
    gap: 10,
  },
  diffSummaryCard: {
    borderRadius: 16,
    padding: 12,
    backgroundColor: "#f6efe8",
    gap: 8,
  },
  diffSummaryRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  diffSummaryPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  diffSummaryLabel: {
    color: "#4f463d",
    fontWeight: "800",
    fontSize: 12,
  },
  diffSummaryText: {
    color: "#6b5a49",
    lineHeight: 20,
  },
  diffCard: {
    borderRadius: 14,
    padding: 12,
    gap: 6,
  },
  diffCardAdded: {
    backgroundColor: "#e5f1ed",
  },
  diffCardRemoved: {
    backgroundColor: "#f6e1dd",
  },
  diffCardChanged: {
    backgroundColor: "#f5eadc",
  },
  diffLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: "#6a5947",
    letterSpacing: 0.6,
  },
  diffSection: {
    color: "#8b755d",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  diffText: {
    color: "#2f2318",
    lineHeight: 21,
  },
  diffBefore: {
    color: "#7f4338",
    lineHeight: 21,
  },
  diffBeforeChanged: {
    backgroundColor: "rgba(190, 80, 64, 0.18)",
  },
  diffAfter: {
    color: "#1f6a3d",
    lineHeight: 21,
  },
  diffAfterChanged: {
    backgroundColor: "rgba(31, 106, 61, 0.18)",
  },
  diffArrow: {
    color: "#7b6a57",
    fontWeight: "700",
  },
  markdownCodeBlock: {
    backgroundColor: "#2b241f",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  markdownCodeLanguage: {
    color: "#d8c4ae",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  markdownCodeLine: {
    color: "#f5ede3",
    fontSize: 13,
    lineHeight: 20,
    fontFamily: "monospace",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(34, 25, 18, 0.45)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#fff8f1",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 22,
    gap: 12,
  },
  modalTitle: {
    fontSize: 22,
    color: "#2f2318",
    fontFamily: "serif",
    fontWeight: "700",
  },
  modalHint: { color: "#705a45", lineHeight: 21 },
  input: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dcc9b0",
    backgroundColor: "#fffdfa",
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#2f2318",
  },
  modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10, marginTop: 6 },
  busyOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(48, 34, 22, 0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  buildBadge: {
    position: "absolute",
    top: 10,
    right: 12,
    borderRadius: 12,
    backgroundColor: "rgba(47, 35, 24, 0.86)",
    paddingHorizontal: 10,
    paddingVertical: 7,
    zIndex: 20,
    elevation: 8,
  },
  buildBadgeText: {
    color: "#fff6ec",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
});
