import { StyleSheet } from "react-native";

const FONT_SANS =
  '"Pretendard GOV Variable", "Pretendard GOV", -apple-system, BlinkMacSystemFont, system-ui, Roboto, "Helvetica Neue", "Segoe UI", "Apple SD Gothic Neo", "Noto Sans KR", "Malgun Gothic", sans-serif';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#f6ede1" },
  safeAreaDark: { backgroundColor: "#201a16" },
  scrollView: { flex: 1 },
  scrollContent: { padding: 18, gap: 14 },
  scrollContentTablet: {
    paddingHorizontal: 28,
    paddingTop: 22,
    paddingBottom: 26,
  },
  scrollContentDesktop: {
    width: "100%",
    maxWidth: 1600,
    alignSelf: "center",
    paddingHorizontal: 16,
  },
  loadingShell: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f6ede1",
    gap: 12,
  },
  loadingLabel: { fontSize: 16, color: "#5d4a38" },
  backgroundOrbA: {
    position: "absolute",
    top: -50,
    right: -20,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "#f1c28d",
    opacity: 0.35,
  },
  backgroundOrbB: {
    position: "absolute",
    bottom: 90,
    left: -50,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "#d2e4d1",
    opacity: 0.45,
  },
  heroCard: {
    backgroundColor: "#fff8f1",
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    borderColor: "#e8d7bf",
    shadowColor: "#7c5230",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  heroCardDesktop: {
    padding: 28,
  },
  eyebrow: {
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: "#b45e20",
    fontWeight: "700",
    marginBottom: 10,
  },
  heroTitle: {
    fontSize: 30,
    lineHeight: 36,
    color: "#2f2318",
    fontFamily: FONT_SANS,
    fontWeight: "700",
  },
  heroSubtitle: { marginTop: 10, color: "#5d4a38", fontSize: 15, lineHeight: 22 },
  heroChecklist: {
    marginTop: 14,
    gap: 6,
  },
  heroChecklistItem: {
    color: "#6a5642",
    fontSize: 13,
    lineHeight: 20,
  },
  heroActions: { flexDirection: "row", gap: 10, marginTop: 18, flexWrap: "wrap" },
  serverHint: { marginTop: 14, color: "#7c6a55", fontSize: 12 },
  workspaceToolbar: {
    backgroundColor: "#fff8f1",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: "#e8d7bf",
    gap: 4,
  },
  workspaceToolbarDesktop: {
    alignItems: "stretch",
  },
  workspaceToolbarDark: {
    backgroundColor: "#2a221d",
    borderColor: "#45362b",
  },
  toolbarShell: {
    position: "relative",
  },
  workspaceToolbarBar: {
    gap: 0,
  },
  workspaceToolbarMain: {
    gap: 8,
  },
  workspaceToolbarTopRow: {
    gap: 6,
  },
  workspaceToolbarTopRowDesktop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  workspaceToolbarBrand: {
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 2,
    flexShrink: 0,
  },
  workspaceToolbarTitle: {
    fontSize: 30,
    lineHeight: 36,
    color: "#2f2318",
    fontFamily: FONT_SANS,
    fontWeight: "700",
  },
  workspaceToolbarTagline: {
    fontSize: 12,
    lineHeight: 16,
    color: "#9a6a3a",
    fontFamily: FONT_SANS,
    fontWeight: "400",
    fontStyle: "normal",
  },
  workspaceToolbarTaglineDark: {
    color: "#d7b38a",
  },
  workspaceToolbarTitleDark: {
    color: "#f5e6d6",
  },
  workspaceToolbarStatus: {
    color: "#7b664f",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  workspaceToolbarStatusDark: {
    color: "#d7b995",
  },
  workspaceToolbarDocument: {
    color: "#806b56",
    fontSize: 12,
    fontWeight: "600",
  },
  workspaceToolbarDocumentDark: {
    color: "#d8c1a7",
  },
  workspaceToolbarDocumentRow: {
    minHeight: 18,
    justifyContent: "center",
  },
  workspaceToolbarCluster: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    minWidth: 0,
  },
  workspaceToolbarActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    flex: 1,
    minWidth: 0,
  },
  workspaceToolbarUtility: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    justifyContent: "flex-end",
    flexWrap: "wrap",
    flexShrink: 1,
    maxWidth: "100%",
  },
  workspaceToolbarPrimaryUtility: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexWrap: "wrap",
  },
  workspaceModeGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingRight: 4,
    marginRight: 2,
  },
  workspaceModeGroupDark: {},
  workspaceModeButton: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#efe5d8",
    borderWidth: 1,
    borderColor: "#dfcfbb",
  },
  workspaceModeButtonDark: {
    backgroundColor: "#3a3028",
    borderColor: "#4a3b2f",
  },
  workspaceModeButtonActive: {
    backgroundColor: "#2e6758",
    borderColor: "#2e6758",
  },
  workspaceModeLabel: {
    color: "#5a4535",
    fontWeight: "700",
    fontSize: 11,
  },
  workspaceModeLabelDark: {
    color: "#e8d7c4",
  },
  workspaceModeLabelActive: {
    color: "#f8f5ef",
  },
  workspaceToolbarSecondaryUtility: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexWrap: "nowrap",
    paddingLeft: 10,
    paddingRight: 4,
    borderLeftWidth: 1,
    borderLeftColor: "#dccab3",
    flexShrink: 0,
  },
  workspaceToolbarSecondaryUtilityDark: {
    borderLeftColor: "#4a3b2f",
  },
  workspaceTabsRow: {
    flexDirection: "row",
    gap: 4,
    flexWrap: "wrap",
  },
  workspaceToolbarInlineDivider: {
    width: 1,
    alignSelf: "stretch",
    backgroundColor: "#dccab3",
    marginHorizontal: 4,
    minHeight: 28,
  },
  workspaceToolbarInlineDividerDark: {
    backgroundColor: "#4a3b2f",
  },
  workspaceTabButton: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#efe5d8",
  },
  workspaceTabButtonDark: {
    backgroundColor: "#3a3028",
  },
  workspaceTabButtonActive: {
    backgroundColor: "#2e6758",
  },
  workspaceTabLabel: {
    color: "#5a4535",
    fontWeight: "700",
    fontSize: 11,
  },
  workspaceTabLabelDark: { color: "#e8d7c4" },
  workspaceTabLabelActive: {
    color: "#f8f5ef",
  },
  utilityButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#dfcfbb",
    backgroundColor: "#fbf4ec",
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexShrink: 0,
  },
  utilityButtonDark: {
    backgroundColor: "#2e2620",
    borderColor: "#47382c",
  },
  utilityButtonLabel: {
    color: "#6b5743",
    fontSize: 11,
    fontWeight: "700",
  },
  utilityIconButton: {
    minWidth: 34,
    paddingHorizontal: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  utilityGithubImage: {
    width: 16,
    height: 16,
  },
  utilityIconLabel: {
    fontSize: 14,
    lineHeight: 16,
  },
  utilityInfoImage: {
    width: 40,
    height: 40,
    marginLeft: -5,
    marginTop: -2,
  },
  utilityInfoCrop: {
    width: 18,
    height: 18,
    borderRadius: 9,
    overflow: "hidden",
  },
  utilityButtonLabelDark: {
    color: "#e6d2bb",
  },
  noticeBox: {
    position: "absolute",
    right: 10,
    bottom: -10,
    zIndex: 20,
    borderRadius: 14,
    backgroundColor: "#f6e9da",
    color: "#6d3d17",
    paddingHorizontal: 12,
    paddingVertical: 8,
    lineHeight: 20,
    borderWidth: 1,
    borderColor: "#e7cfb4",
    shadowColor: "#53321a",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    maxWidth: 420,
    fontSize: 12,
  },
  noticeBoxDark: {
    backgroundColor: "#3a2f27",
    borderColor: "#5a493d",
    color: "#f0e1d1",
  },
  primaryButton: {
    backgroundColor: "#a9561d",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  primaryButtonLabel: { color: "#fffaf4", fontWeight: "700", fontSize: 11 },
  disabledButtonLabel: { opacity: 0.55 },
  secondaryButton: {
    backgroundColor: "#f3e9dd",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#e5d6c4",
  },
  secondaryButtonDark: {
    backgroundColor: "#342b24",
    borderColor: "#49392d",
  },
  toolbarDisabledButton: {
    opacity: 0.5,
  },
  toolbarDisabledButtonLabel: {
    opacity: 0.8,
  },
  secondaryButtonCompact: {
    minWidth: 36,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonSoft: {
    opacity: 0.9,
  },
  secondaryButtonSoftDark: {
    backgroundColor: "#2f2721",
  },
  secondaryButtonLabel: { color: "#5a3f2a", fontWeight: "700", fontSize: 11 },
  secondaryButtonLabelDark: { color: "#ead8c4", fontWeight: "700", fontSize: 11 },
  sectionRow: { gap: 18 },
  sectionRowDesktop: {},
  column: { gap: 10 },
  columnWide: { gap: 10, flex: 1 },
  detailColumnDesktop: {
    minWidth: 0,
    flex: 1,
  },
  listColumnDesktop: {
    width: "100%",
    flexShrink: 1,
  },
  jobsOverlayDesktop: {
    position: "absolute",
    top: 92,
    right: 16,
    width: 360,
    zIndex: 20,
  },
  sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  detailHeaderBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sectionTitle: {
    fontSize: 22,
    color: "#2f2318",
    fontFamily: FONT_SANS,
    fontWeight: "700",
  },
  sectionTitleDark: { color: "#f2e2d0" },
  sectionMeta: { color: "#7c6a55", fontSize: 12, fontWeight: "700" },
  sectionMetaDark: { color: "#cdb396", fontSize: 12, fontWeight: "700" },
  panel: {
    backgroundColor: "#fffbf7",
    borderWidth: 1,
    borderColor: "#eadcc6",
    borderRadius: 24,
    padding: 12,
    gap: 10,
  },
  panelDark: {
    backgroundColor: "#2a221d",
    borderColor: "#45362b",
  },
  listControlsShell: {
    gap: 10,
  },
  paletteTitle: {
    color: "#8a7661",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  paletteTitleDark: { color: "#ccb090" },
  listControlsShellDesktop: {
    paddingBottom: 2,
  },
  listSelectionHint: {
    color: "#7d6954",
    fontSize: 12,
    lineHeight: 18,
  },
  listSelectionHintDark: { color: "#ccb398" },
  listControlsDivider: {
    height: 1,
    backgroundColor: "#eadcc6",
  },
  listScrollArea: {
    minHeight: 120,
  },
  listScrollContent: {
    gap: 10,
    paddingBottom: 2,
  },
  jobTableHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingBottom: 2,
  },
  jobTableHeaderText: {
    color: "#8a7661",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  jobTableHeaderTextDark: { color: "#ccb090" },
  jobTableHeaderStatus: {
    width: 82,
    flexShrink: 0,
  },
  jobTableHeaderFilename: {
    flex: 1,
    minWidth: 0,
  },
  jobTableHeaderTimestamp: {
    width: 94,
    flexShrink: 0,
    textAlign: "right",
  },
  desktopPanelScrollArea: {
    maxHeight: 640,
  },
  listSearchInput: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#dcc9b0",
    backgroundColor: "#fffdfa",
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#2f2318",
  },
  listSearchInputDark: {
    backgroundColor: "#201a16",
    borderColor: "#4b3a2c",
    color: "#f2e4d4",
  },
  listFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  listFilterChip: {
    borderRadius: 999,
    backgroundColor: "#f1e5d8",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  listFilterChipDark: {
    backgroundColor: "#3a3028",
  },
  listFilterChipActive: {
    backgroundColor: "#2e6758",
  },
  listFilterChipLabel: {
    color: "#6f5a48",
    fontSize: 12,
    fontWeight: "700",
  },
  listFilterChipLabelDark: { color: "#dfcab3" },
  listFilterChipLabelActive: {
    color: "#fffaf4",
  },
  listSortButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d4c3ae",
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "#fff8f1",
  },
  listSortButtonDark: {
    backgroundColor: "#2f2721",
    borderColor: "#4b3a2c",
  },
  listSortButtonLabel: {
    color: "#5a3f2a",
    fontWeight: "700",
    fontSize: 12,
  },
  listSortButtonLabelDark: { color: "#ead8c4" },
  panelLarge: {
    backgroundColor: "#fffbf7",
    borderWidth: 1,
    borderColor: "#eadcc6",
    borderRadius: 24,
    padding: 14,
    gap: 12,
    minHeight: 420,
  },
  panelLargeDark: {
    backgroundColor: "#2a221d",
    borderColor: "#45362b",
  },
  panelLargeDesktop: {
    minHeight: 720,
  },
  stateCardNeutral: {
    borderRadius: 20,
    padding: 20,
    backgroundColor: "#f6efe8",
    gap: 8,
    borderWidth: 1,
    borderColor: "#eadcc6",
  },
  stateCardNeutralDark: {
    backgroundColor: "#352c25",
    borderColor: "#4b3d31",
  },
  stateCardProcessing: {
    borderRadius: 20,
    backgroundColor: "#e4f2ef",
    padding: 18,
    gap: 10,
    borderWidth: 1,
    borderColor: "#b9d7d3",
  },
  stateCardProcessingDark: {
    backgroundColor: "#233431",
    borderColor: "#3d5b55",
  },
  stateCardError: {
    borderRadius: 20,
    backgroundColor: "#f7dfdc",
    padding: 18,
    gap: 10,
    borderWidth: 1,
    borderColor: "#dfb0aa",
  },
  stateCardErrorDark: {
    backgroundColor: "#3b2825",
    borderColor: "#6b4641",
  },
  stateCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  stateEyebrow: {
    color: "#7b664f",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
  },
  stateEyebrowDark: {
    color: "#ccb090",
  },
  stateTitle: {
    fontSize: 20,
    lineHeight: 28,
    color: "#2f2318",
    fontFamily: FONT_SANS,
    fontWeight: "700",
  },
  stateTitleDark: { color: "#f2e2d0" },
  stateBody: {
    color: "#5f5144",
    lineHeight: 22,
  },
  stateBodyDark: { color: "#d7c2ab", lineHeight: 22 },
  markdownIntroTitle: {
    fontSize: 17,
    lineHeight: 26,
    color: "#2f2318",
    fontWeight: "700",
    fontFamily: FONT_SANS,
  },
  markdownIntroTitleDark: {
    color: "#f2e2d0",
  },
  emptyDetailChecklist: {
    marginTop: 8,
    gap: 6,
  },
  emptyDetailChecklistItem: {
    color: "#6f5b48",
    lineHeight: 20,
  },
  emptyDetailChecklistItemDark: {
    color: "#cdbfae",
  },
  emptyDetailDivider: {
    height: 1,
    backgroundColor: "#e3d2bc",
    marginVertical: 4,
  },
  emptyDetailDividerDark: {
    backgroundColor: "#4b3d31",
  },
  emptyExampleTable: {
    borderWidth: 1,
    borderColor: "#ddd6cc",
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#fffdfa",
    alignSelf: "flex-start",
    width: "100%",
    minWidth: 640,
    maxWidth: 920,
  },
  emptyExampleTableScrollWrap: {
    width: "100%",
  },
  emptyExampleTableScroll: {
    paddingBottom: 2,
  },
  emptyExampleTableDark: {
    borderColor: "#4b3d31",
    backgroundColor: "#2a231d",
  },
  emptyExampleHeaderRow: {
    backgroundColor: "#f8f6f2",
  },
  emptyExampleHeaderRowDark: {
    backgroundColor: "#342b24",
  },
  emptyExampleRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e7e0d6",
  },
  emptyExampleRowDark: {
    borderBottomColor: "#4b3d31",
  },
  emptyExampleRowLast: {
    borderBottomWidth: 0,
  },
  emptyExampleCell: {
    flex: 1,
    minWidth: 180,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRightWidth: 1,
    borderRightColor: "#e7e0d6",
    justifyContent: "center",
  },
  emptyExampleCellDark: {
    borderRightColor: "#4b3d31",
  },
  emptyExampleHeaderCell: {
    borderBottomWidth: 1,
    borderBottomColor: "#d9d1c6",
  },
  emptyExampleCellLast: {
    borderRightWidth: 0,
  },
  emptyExampleHeaderText: {
    color: "#4f463d",
    fontWeight: "700",
    fontSize: 12,
    lineHeight: 18,
  },
  emptyExampleHeaderTextDark: {
    color: "#eadfce",
  },
  emptyExampleLabel: {
    color: "#5f5144",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  emptyExampleLabelDark: {
    color: "#d7c2ab",
  },
  emptyExampleCode: {
    fontFamily: "monospace",
    color: "#6d3d17",
    fontSize: 13,
    lineHeight: 19,
  },
  emptyExampleCodeDark: {
    color: "#f1d7b2",
  },
  emptyExamplePreviewTitle: {
    color: "#2f2318",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily: FONT_SANS,
  },
  emptyExamplePreviewTitleDark: {
    color: "#f2e2d0",
  },
  emptyExamplePreviewText: {
    color: "#2f2318",
    fontSize: 14,
    lineHeight: 20,
  },
  emptyExamplePreviewTextDark: {
    color: "#eadfce",
  },
  emptyExamplePreviewStrong: {
    fontWeight: "700",
  },
  emptyExamplePreviewQuote: {
    color: "#6f6256",
    fontSize: 14,
    lineHeight: 20,
    fontStyle: "italic",
    borderLeftWidth: 3,
    borderLeftColor: "#cfc4b6",
    paddingLeft: 10,
  },
  emptyExamplePreviewQuoteDark: {
    color: "#cdbfae",
    borderLeftColor: "#6a5b4f",
  },
  emptyExamplePreviewRule: {
    height: 1,
    backgroundColor: "#e3d2bc",
  },
  emptyExamplePreviewRuleDark: {
    backgroundColor: "#4b3d31",
  },
  progressSteps: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  progressStepsStack: {
    flexDirection: "column",
  },
  progressStep: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  progressStepActive: {
    backgroundColor: "#2e6758",
  },
  progressStepPending: {
    backgroundColor: "rgba(46, 103, 88, 0.12)",
  },
  progressStepLabel: {
    color: "#f7efe6",
    fontWeight: "700",
    fontSize: 12,
  },
  jobCard: { borderRadius: 18, backgroundColor: "#f8efe6", padding: 14, gap: 8 },
  jobCardDark: { backgroundColor: "#352c25" },
  jobCardSelected: { backgroundColor: "#f2dcc2", borderWidth: 1, borderColor: "#d19259" },
  jobRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 16,
    backgroundColor: "#f8efe6",
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "transparent",
  },
  jobRowDark: {
    backgroundColor: "#352c25",
  },
  jobRowSelected: {
    backgroundColor: "#f2dcc2",
    borderColor: "#d19259",
  },
  jobRowStatusCell: {
    width: 82,
    flexShrink: 0,
  },
  jobRowFilenameCell: {
    flex: 1,
    minWidth: 0,
  },
  jobRowTimestampCell: {
    width: 94,
    flexShrink: 0,
    alignItems: "flex-end",
  },
  jobCardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 },
  jobTimestamp: { color: "#887561", fontSize: 11 },
  jobTimestampDark: { color: "#ccb090", fontSize: 11 },
  jobFilename: { color: "#36281d", fontSize: 14, lineHeight: 19, fontWeight: "600" },
  jobFilenameDark: { color: "#f0e0cf", fontSize: 14, lineHeight: 19, fontWeight: "600" },
  loadMoreButton: { paddingVertical: 12, alignItems: "center" },
  loadMoreLabel: { color: "#8b5c2e", fontWeight: "700" },
  loadMoreLabelDark: { color: "#ddb98b", fontWeight: "700" },
  policyBriefingMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  policyBriefingMetaText: {
    color: "#7c6a55",
    fontSize: 12,
    lineHeight: 18,
  },
  policyBriefingList: {
    maxHeight: 420,
    marginTop: 8,
  },
  policyBriefingListContent: {
    gap: 8,
    paddingVertical: 4,
  },
  policyBriefingEmptyState: {
    minHeight: 96,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  policyBriefingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#e4d5c1",
    borderRadius: 14,
    backgroundColor: "#fff8f1",
  },
  policyBriefingRowBody: {
    flex: 1,
    gap: 4,
  },
  policyBriefingRowAction: {
    justifyContent: "center",
    alignItems: "flex-end",
    minWidth: 56,
  },
  policyBriefingTitle: {
    color: "#36281d",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  policyBriefingAppendix: {
    color: "#2e6758",
    fontSize: 11,
    fontWeight: "700",
  },
  emptyState: { color: "#7c6a55", lineHeight: 22 },
  emptyStateDark: { color: "#ccb398", lineHeight: 22 },
  detailHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  detailHeaderMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  detailTopCluster: {
    gap: 12,
  },
  detailStickyShell: {
    gap: 12,
  },
  detailStickyShellDesktop: {
    paddingBottom: 2,
  },
  detailTopClusterDesktop: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 14,
  },
  detailControlsCluster: {
    flex: 1,
    gap: 12,
    minWidth: 0,
  },
  backButton: {
    backgroundColor: "#efe1d1",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  backButtonLabel: {
    color: "#5a3f2a",
    fontWeight: "700",
    fontSize: 12,
  },
  detailTitle: {
    fontSize: 21,
    lineHeight: 28,
    color: "#2f2318",
    fontFamily: FONT_SANS,
    fontWeight: "700",
  },
  detailSub: { marginTop: 6, color: "#887561" },
  processingBox: {
    borderRadius: 18,
    backgroundColor: "#e2f0ef",
    padding: 16,
    gap: 10,
    alignItems: "center",
  },
  processingLabel: { color: "#0f5656", textAlign: "center", lineHeight: 21 },
  errorBox: { borderRadius: 18, backgroundColor: "#f7dfdc", padding: 16, gap: 10 },
  errorTitle: { color: "#8e2020", fontWeight: "800", fontSize: 16 },
  errorBody: { color: "#713535", lineHeight: 20 },
  tabRow: { flexDirection: "row", gap: 8 },
  tabButton: {
    flex: 1,
    borderRadius: 999,
    paddingVertical: 12,
    backgroundColor: "#efe5d8",
    alignItems: "center",
  },
  tabButtonDark: {
    backgroundColor: "#3a3028",
  },
  tabButtonActive: { backgroundColor: "#2e6758" },
  tabLabel: { color: "#5a4535", fontWeight: "700" },
  tabLabelDark: { color: "#ead8c4", fontWeight: "700" },
  tabLabelActive: { color: "#f8f5ef" },
  resultMetaCard: { borderRadius: 18, padding: 14, backgroundColor: "#f6efe8", gap: 6 },
  resultMetaCardDark: {
    backgroundColor: "#352c25",
  },
  resultMetaCardDesktop: {
    width: 340,
    flexShrink: 0,
  },
  resultMetaEyebrow: {
    color: "#8a7661",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  resultMetaEyebrowDark: { color: "#ccb090" },
  resultMetaTitle: { color: "#34261c", fontSize: 18, fontWeight: "700" },
  resultMetaTitleDark: { color: "#f2e2d0", fontSize: 18, fontWeight: "700" },
  resultMetaBody: { color: "#705a45", lineHeight: 20 },
  resultMetaBodyDark: { color: "#d7c2ab", lineHeight: 20 },
  detailActionsHeader: {
    gap: 4,
  },
  detailActionsTitle: {
    color: "#2f2318",
    fontSize: 18,
    fontWeight: "700",
  },
  detailActionsTitleDark: { color: "#f2e2d0" },
  detailActionsHint: {
    color: "#75624f",
    lineHeight: 20,
  },
  detailActionsHintDark: { color: "#ccb398", lineHeight: 20 },
  editorToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  editorToolbarDesktop: {
    gap: 12,
    alignItems: "stretch",
  },
  editorToolGroup: {
    borderRadius: 16,
    backgroundColor: "#f7efe5",
    borderWidth: 1,
    borderColor: "#e6d6c0",
    padding: 10,
    gap: 8,
  },
  editorToolGroupLabel: {
    color: "#8a7661",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  editorToolGroupButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  editorToolButton: {
    backgroundColor: "#f0e4d6",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  editorToolLabel: {
    color: "#5a3f2a",
    fontWeight: "700",
    fontSize: 12,
  },
  sectionJumpRow: {
    gap: 8,
    paddingVertical: 2,
  },
  sectionJumpButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#dbcbb5",
    backgroundColor: "#fff8f1",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  sectionJumpLabel: {
    color: "#705a45",
    fontSize: 12,
    fontWeight: "700",
  },
  editor: {
    minHeight: 220,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#d9c7ad",
    backgroundColor: "#fffdfa",
    padding: 14,
    fontSize: 16,
    lineHeight: 26,
    color: "#2f2318",
  },
  editorDark: {
    color: "#f2e2d0",
  },
  editorDesktop: {
    minHeight: 520,
    flex: 1,
    borderWidth: 0,
    backgroundColor: "transparent",
    padding: 0,
    paddingTop: 2,
    paddingRight: 10,
  },
  editorTablet: {
    minHeight: 260,
    flex: 1,
    borderWidth: 0,
    backgroundColor: "transparent",
    padding: 0,
    paddingTop: 2,
    paddingRight: 6,
  },
  editorMobile: {
    minHeight: 460,
    flex: 1,
    borderWidth: 0,
    backgroundColor: "transparent",
    padding: 0,
    paddingTop: 2,
    paddingRight: 4,
  },
  editorSplitLayout: {
    flexDirection: "row",
    gap: 0,
    alignItems: "stretch",
    justifyContent: "center",
    minHeight: 722,
  },
  editorStackLayout: {
    gap: 12,
    minHeight: 0,
  },
  editorPanel: {
    flexGrow: 0,
    flexShrink: 0,
    width: "46%",
    minWidth: 620,
    maxWidth: 860,
    borderRadius: 20,
    backgroundColor: "#fffdfa",
    borderWidth: 1,
    borderColor: "#e4d4bf",
    padding: 14,
    gap: 10,
    minHeight: 0,
  },
  editorPanelDesktop: {
    width: undefined,
    minWidth: 360,
    maxWidth: undefined,
    flexGrow: 1,
  },
  editorPanelDark: {
    backgroundColor: "#241e19",
    borderColor: "#46392d",
  },
  editorPanelTablet: {
    width: "100%",
    minWidth: 0,
    maxWidth: undefined,
    minHeight: 280,
  },
  editorPanelMobile: {
    width: "100%",
    minWidth: 0,
    maxWidth: undefined,
    minHeight: 520,
  },
  previewPanel: {
    borderRadius: 20,
    backgroundColor: "#fffdfa",
    borderWidth: 1,
    borderColor: "#e4d4bf",
    padding: 14,
    gap: 10,
    minHeight: 240,
  },
  previewPanelDark: {
    backgroundColor: "#241e19",
    borderColor: "#46392d",
  },
  previewPanelDesktop: {
    flexGrow: 1,
    flexShrink: 0,
    width: undefined,
    minWidth: 360,
    maxWidth: undefined,
    minHeight: 0,
  },
  previewPanelSplit: {
    minHeight: 722,
  },
  desktopResizeHandle: {
    width: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  desktopResizeTrack: {
    width: 6,
    alignSelf: "stretch",
    borderRadius: 999,
    backgroundColor: "#d9c7ad",
    marginVertical: 20,
  },
  desktopResizeTrackDark: {
    backgroundColor: "#5f4f40",
  },
  previewPanelTablet: {
    width: "100%",
    minWidth: 0,
    maxWidth: undefined,
    minHeight: 300,
  },
  previewPanelMobile: {
    minHeight: 420,
  },
  splitPanelBody: {
    flex: 1,
    paddingTop: 4,
  },
  previewLabel: {
    color: "#7b664f",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  previewLabelDark: {
    color: "#ccb090",
  },
  previewScroll: { maxHeight: 360 },
  previewScrollDesktop: {
    maxHeight: 702,
  },
  previewScrollTablet: {
    maxHeight: 360,
  },
  previewScrollMobile: {
    maxHeight: 620,
  },
  previewScrollContent: {
    paddingTop: 2,
    paddingBottom: 6,
    paddingRight: 10,
  },
  dragOverlay: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(15, 61, 52, 0.18)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    zIndex: 60,
  },
  dragOverlayCard: {
    width: "100%",
    maxWidth: 640,
    borderRadius: 28,
    borderWidth: 3,
    borderStyle: "dashed",
    borderColor: "#2e6758",
    backgroundColor: "rgba(255, 252, 246, 0.96)",
    paddingHorizontal: 28,
    paddingVertical: 32,
    gap: 10,
    alignItems: "center",
  },
  dragOverlayEyebrow: {
    color: "#2e6758",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  dragOverlayTitle: {
    color: "#2f2318",
    fontSize: 28,
    lineHeight: 36,
    fontWeight: "800",
    textAlign: "center",
  },
  dragOverlayBody: {
    color: "#705a45",
    fontSize: 15,
    lineHeight: 24,
    textAlign: "center",
  },
  emptyDropZone: {
    borderRadius: 24,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "#c8a77d",
    backgroundColor: "#fff7ec",
    paddingHorizontal: 22,
    paddingVertical: 22,
    gap: 8,
    marginBottom: 18,
  },
  emptyDropZoneDark: {
    backgroundColor: "#31271f",
    borderColor: "#8f7154",
  },
  emptyDropZoneEyebrow: {
    color: "#9a6a3a",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.1,
  },
  emptyDropZoneEyebrowDark: {
    color: "#d7b38a",
  },
  emptyDropZoneTitle: {
    color: "#5a3b22",
    fontSize: 22,
    lineHeight: 30,
    fontWeight: "800",
  },
  emptyDropZoneTitleDark: {
    color: "#f2ddc4",
  },
  emptyDropZoneBody: {
    color: "#7a6148",
    lineHeight: 22,
  },
  emptyDropZoneBodyDark: {
    color: "#d2b89c",
  },
  previewText: { color: "#2f2318", fontSize: 16, lineHeight: 26 },
  previewTextDark: { color: "#eadfce" },
  previewEmpty: { color: "#7c6a55", lineHeight: 22 },
  previewEmptyDark: { color: "#ccb398" },
  markdownPreview: { gap: 12 },
  markdownActiveBlock: {
    backgroundColor: "#fff0a8",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginHorizontal: -8,
  },
  markdownActiveBlockDark: {
    backgroundColor: "#4e4418",
  },
  markdownHeading: {
    color: "#2f2318",
    fontFamily: FONT_SANS,
    fontWeight: "700",
  },
  markdownHeadingDark: {
    color: "#f2e2d0",
  },
  markdownHeading1: {
    fontSize: 30,
    lineHeight: 38,
  },
  markdownHeading2: {
    fontSize: 25,
    lineHeight: 33,
  },
  markdownHeading3: {
    fontSize: 18,
    lineHeight: 26,
  },
  markdownParagraph: {
    color: "#2f2318",
    fontSize: 16,
    lineHeight: 26,
  },
  markdownParagraphDark: {
    color: "#eadfce",
  },
  mobileActionBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
    paddingTop: 8,
  },
  mobileActionBarDark: {},
  mobileSaveButton: {
    minWidth: 120,
  },
  mobileActionButton: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d9c7ad",
    backgroundColor: "#f6ede1",
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  mobileActionButtonDark: {
    backgroundColor: "#302822",
    borderColor: "#4b3d31",
  },
  mobileActionLabel: {
    color: "#5a3f2a",
    fontWeight: "700",
    fontSize: 13,
  },
  mobileActionLabelDark: {
    color: "#ead8c4",
  },
  markdownStrong: {
    fontWeight: "700",
    color: "#24190f",
  },
  markdownStrongDark: {
    color: "#fff3e6",
  },
  markdownEmphasis: {
    fontStyle: "italic",
  },
  markdownStrike: {
    textDecorationLine: "line-through",
    color: "#7b7064",
  },
  markdownStrikeDark: {
    color: "#b8ab9f",
  },
  markdownInlineCode: {
    fontFamily: "monospace",
    backgroundColor: "#f1e6d8",
    color: "#6d3d17",
  },
  markdownInlineCodeDark: {
    backgroundColor: "#3a3028",
    color: "#f1d7b2",
  },
  markdownLink: {
    color: "#0f6f6f",
    textDecorationLine: "underline",
  },
  markdownLinkDark: {
    color: "#7fd7d0",
  },
  markdownCheckbox: {
    width: 18,
    height: 18,
    marginTop: 4,
    borderWidth: 1,
    borderColor: "#b5a695",
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fffdfa",
  },
  markdownCheckboxDark: {
    borderColor: "#7d6d5f",
    backgroundColor: "#2d2621",
  },
  markdownCheckboxChecked: {
    backgroundColor: "#d7e8e2",
    borderColor: "#7aa396",
  },
  markdownCheckboxMark: {
    color: "#2e6758",
    fontSize: 12,
    fontWeight: "700",
  },
  markdownCheckboxMarkDark: {
    color: "#95d2be",
  },
  markdownChecklistDone: {
    color: "#7b7064",
    textDecorationLine: "line-through",
  },
  markdownChecklistDoneDark: {
    color: "#b8ab9f",
  },
  markdownQuote: {
    borderLeftWidth: 3,
    borderLeftColor: "#cfc4b6",
    paddingVertical: 6,
    paddingLeft: 14,
    paddingRight: 4,
    marginVertical: 2,
  },
  markdownQuoteDark: {
    borderLeftColor: "#6a5b4f",
  },
  markdownQuoteText: {
    color: "#6f6256",
    fontSize: 14,
    lineHeight: 22,
    fontStyle: "italic",
  },
  markdownQuoteTextDark: {
    color: "#cdbfae",
  },
  markdownQuoteParagraph: {
    marginTop: 8,
  },
  markdownQuoteLine: {
    marginTop: 2,
  },
  markdownList: {
    gap: 8,
  },
  markdownListItem: {
    flexDirection: "row",
    gap: 4,
    alignItems: "flex-start",
  },
  markdownListBullet: {
    minWidth: 14,
    color: "#8b5c2e",
    fontWeight: "700",
    lineHeight: 24,
  },
  markdownListBulletDark: {
    color: "#ddb98b",
  },
  markdownListText: {
    color: "#2f2318",
    fontSize: 16,
    lineHeight: 26,
  },
  markdownListTextDark: {
    color: "#eadfce",
  },
  markdownListTextWrap: {
    flex: 1,
  },
  markdownRule: {
    height: 1,
    backgroundColor: "#e3d2bc",
    marginVertical: 4,
  },
  markdownRuleDark: {
    backgroundColor: "#4b3d31",
  },
  markdownTable: {
    borderWidth: 1,
    borderColor: "#ddd6cc",
    borderRadius: 6,
    overflow: "hidden",
    backgroundColor: "#fffdfa",
    width: "100%",
    alignSelf: "stretch",
  },
  markdownTableDark: {
    borderColor: "#4b3d31",
    backgroundColor: "#2a231d",
  },
  markdownTableWrap: {
    width: "100%",
    alignSelf: "stretch",
  },
  markdownHtmlFrameWrap: {
    width: "100%",
    alignSelf: "stretch",
    borderWidth: 1,
    borderColor: "#d8c4ab",
    borderRadius: 6,
    overflow: "hidden",
    backgroundColor: "#fffdf8",
  },
  markdownHtmlFrameWrapDark: {
    borderColor: "#5d4b3d",
    backgroundColor: "#241d18",
  },
  markdownTableScrollContent: {
    minWidth: "100%",
    flexGrow: 1,
  },
  markdownTableHeaderRow: {
    backgroundColor: "#f8f6f2",
  },
  markdownTableHeaderRowDark: {
    backgroundColor: "#342b24",
  },
  markdownTableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e7e0d6",
  },
  markdownTableRowDark: {
    borderBottomColor: "#4b3d31",
  },
  markdownTableRowLast: {
    borderBottomWidth: 0,
  },
  markdownTableCell: {
    flex: 1,
    minWidth: 140,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRightWidth: 1,
    borderRightColor: "#e7e0d6",
    justifyContent: "center",
  },
  markdownTableCellDark: {
    borderRightColor: "#4b3d31",
  },
  markdownTableHeaderCell: {
    borderBottomWidth: 1,
    borderBottomColor: "#d9d1c6",
  },
  markdownTableHeaderCellDark: {
    borderBottomColor: "#58483b",
  },
  markdownTableCellLast: {
    borderRightWidth: 0,
  },
  markdownTableHeaderText: {
    color: "#4f463d",
    fontWeight: "700",
    lineHeight: 20,
  },
  markdownTableHeaderTextDark: {
    color: "#eadfce",
  },
  markdownTableCellText: {
    color: "#2f2318",
    lineHeight: 21,
  },
  markdownTableCellTextDark: {
    color: "#eadfce",
  },
  markdownTableTextLeft: {
    textAlign: "left",
  },
  markdownTableTextCenter: {
    textAlign: "center",
  },
  markdownTableTextRight: {
    textAlign: "right",
  },
  markdownImageWrap: {
    gap: 8,
  },
  markdownImageFallback: {
    borderWidth: 1,
    borderColor: "#ddd6cc",
    borderRadius: 12,
    padding: 14,
    gap: 8,
    backgroundColor: "#fbf7f2",
  },
  markdownImageFallbackDark: {
    borderColor: "#4b3d31",
    backgroundColor: "#2a231d",
  },
  markdownImageFallbackTitle: {
    color: "#5f5144",
    fontWeight: "700",
  },
  markdownImageFallbackTitleDark: {
    color: "#eadfce",
  },
  markdownImageFallbackUrl: {
    color: "#7b6a57",
    lineHeight: 18,
  },
  markdownImageFallbackUrlDark: {
    color: "#c3b29f",
  },
  markdownImage: {
    width: "100%",
    minHeight: 180,
    maxHeight: 320,
    borderRadius: 12,
    backgroundColor: "#f7f2eb",
  },
  markdownImageCaption: {
    color: "#7b6a57",
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  markdownImageCaptionDark: {
    color: "#c3b29f",
  },
  editNotice: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  editNoticeDirty: {
    backgroundColor: "#f6e2cf",
  },
  editNoticeClean: {
    backgroundColor: "#e5f1ed",
  },
  editNoticeText: {
    color: "#5f5144",
    lineHeight: 20,
  },
  diffPreview: {
    gap: 10,
  },
  diffSummaryCard: {
    borderRadius: 16,
    padding: 12,
    backgroundColor: "#f6efe8",
    gap: 8,
  },
  diffSummaryCardDark: {
    backgroundColor: "#352c25",
  },
  diffSummaryRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  diffSummaryPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  diffSummaryLabel: {
    color: "#4f463d",
    fontWeight: "800",
    fontSize: 12,
  },
  diffSummaryLabelDark: {
    color: "#eadfce",
  },
  diffSummaryText: {
    color: "#6b5a49",
    lineHeight: 20,
  },
  diffSummaryTextDark: {
    color: "#cdbfae",
  },
  diffCard: {
    borderRadius: 14,
    padding: 12,
    gap: 6,
  },
  diffCardAdded: {
    backgroundColor: "#e5f1ed",
  },
  diffCardRemoved: {
    backgroundColor: "#f6e1dd",
  },
  diffCardChanged: {
    backgroundColor: "#f5eadc",
  },
  diffLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: "#6a5947",
    letterSpacing: 0.6,
  },
  diffLabelDark: {
    color: "#d9c8b5",
  },
  diffSection: {
    color: "#8b755d",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  diffSectionDark: {
    color: "#ccb090",
  },
  diffText: {
    color: "#2f2318",
    lineHeight: 21,
  },
  diffTextDark: {
    color: "#eadfce",
  },
  diffBefore: {
    color: "#7f4338",
    lineHeight: 21,
  },
  diffBeforeDark: {
    color: "#f0b7ad",
  },
  diffBeforeChanged: {
    backgroundColor: "rgba(190, 80, 64, 0.18)",
  },
  diffAfter: {
    color: "#1f6a3d",
    lineHeight: 21,
  },
  diffAfterDark: {
    color: "#9bddb7",
  },
  diffAfterChanged: {
    backgroundColor: "rgba(31, 106, 61, 0.18)",
  },
  diffArrow: {
    color: "#7b6a57",
    fontWeight: "700",
  },
  diffArrowDark: {
    color: "#c3b29f",
  },
  markdownCodeBlock: {
    backgroundColor: "#2b241f",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  markdownCodeLanguage: {
    color: "#d8c4ae",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  markdownCodeLine: {
    color: "#f5ede3",
    fontSize: 13,
    lineHeight: 20,
    fontFamily: "monospace",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(34, 25, 18, 0.45)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalCard: {
    backgroundColor: "#fff8f1",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 22,
    gap: 12,
  },
  modalTitle: {
    fontSize: 22,
    color: "#2f2318",
    fontFamily: FONT_SANS,
    fontWeight: "700",
  },
  modalHint: { color: "#705a45", lineHeight: 21 },
  infoQuote: {
    borderLeftWidth: 3,
    borderLeftColor: "#d2b48b",
    paddingLeft: 12,
    color: "#6e5843",
    fontStyle: "italic",
    lineHeight: 21,
  },
  infoModalCard: {
    width: "100%",
    maxWidth: 540,
    backgroundColor: "#fff8f1",
    borderRadius: 24,
    padding: 22,
    gap: 14,
    borderWidth: 1,
    borderColor: "#e3d1ba",
  },
  infoMetaList: {
    gap: 10,
  },
  infoMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  infoMetaLabel: {
    color: "#7b664f",
    fontSize: 12,
    fontWeight: "800",
  },
  infoMetaValue: {
    color: "#2f2318",
    fontWeight: "700",
  },
  infoMetaLink: {
    color: "#0f6f6f",
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  infoCapabilityList: {
    gap: 8,
  },
  infoCapabilityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  infoCapabilityBadge: {
    minWidth: 56,
    textAlign: "center",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    color: "#fff9f2",
    fontSize: 11,
    fontWeight: "800",
  },
  infoCapabilityGood: {
    backgroundColor: "#2f6b45",
  },
  infoCapabilityLearning: {
    backgroundColor: "#b37c1d",
  },
  infoCapabilityBad: {
    backgroundColor: "#9a3d39",
  },
  infoCapabilityText: {
    color: "#2f2318",
    lineHeight: 20,
  },
  input: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dcc9b0",
    backgroundColor: "#fffdfa",
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#2f2318",
  },
  settingsPresetGroup: {
    gap: 8,
  },
  settingsPresetButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dcc9b0",
    backgroundColor: "#fffdfa",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  settingsPresetButtonActive: {
    borderColor: "#2f6f6f",
    backgroundColor: "#edf8f6",
  },
  settingsPresetRadio: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#bba88a",
    backgroundColor: "transparent",
    flexShrink: 0,
  },
  settingsPresetRadioActive: {
    borderColor: "#c07a30",
    backgroundColor: "#c07a30",
  },
  settingsPresetContent: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  settingsPresetTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  settingsPresetLabel: {
    color: "#2f2318",
    fontWeight: "800",
    fontSize: 13,
  },
  settingsPresetLabelActive: {
    color: "#185a58",
  },
  settingsPresetUrl: {
    color: "#7b664f",
    fontSize: 11,
  },
  settingsPresetUrlActive: {
    color: "#185a58",
  },
  settingsPresetBadge: {
    fontSize: 10,
    fontWeight: "800",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 5,
    color: "#fff",
    backgroundColor: "#c8baa8",
    overflow: "hidden",
  },
  settingsPresetBadgeActive: {
    backgroundColor: "#d4a36a",
  },
  settingsStatusBox: {
    minHeight: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  settingsStatusSpacer: {
    width: 20,
    height: 20,
  },
  settingsStatusText: {
    color: "#7b664f",
    fontSize: 12,
    lineHeight: 18,
    flex: 1,
  },
  settingsStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    flexShrink: 0,
  },
  settingsStatusDotUp: {
    backgroundColor: "#2f9e44",
  },
  settingsStatusDotDown: {
    backgroundColor: "#d94841",
  },
  settingsStatusDotUnknown: {
    backgroundColor: "#c8baa8",
  },
  modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10, marginTop: 6 },
  busyOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(48, 34, 22, 0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  buildBadge: {
    position: "absolute",
    top: 10,
    right: 12,
    borderRadius: 12,
    backgroundColor: "rgba(47, 35, 24, 0.86)",
    paddingHorizontal: 10,
    paddingVertical: 7,
    zIndex: 20,
    elevation: 8,
  },
  buildBadgeText: {
    color: "#fff6ec",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
});
